services:
  backend:
    image: hojiakbar2806/softgroup_backend:latest
    container_name: backend
    command: /bin/sh -c "flask db upgrade && poetry run gunicorn -b 0.0.0.0:8000 run:app"
    environment:
      - FLASK_ENV=production
      - DEBUG=False
      - RUN_ON_POSTGRES=True
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - softgroup_db
    networks:
      - app-network

  frontend:
    image: hojiakbar2806/softgroup:latest
    container_name: frontend
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - app-network

  softgroup_db:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_container:/var/lib/postgresql/data
    networks:
      - app-network

  nginx-softgroup:
    image: nginx:latest
    container_name: nginx-softgroup
    volumes:
      - ./nginx/nginx-softgroup.conf:/etc/nginx/nginx.conf
      - ./nginx/error-pages:/etc/nginx/error-pages:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    networks:
      - app-network

  nginx-templates:
    image: nginx:latest
    container_name: nginx-templates
    volumes:
      - ./nginx/nginx-templates.conf:/etc/nginx/nginx.conf
      - ./nginx/error-pages:/etc/nginx/error-pages:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
