services:
  softgroup_backend:
    image: hojiakbar2806/softgroup_backend:latest
    container_name: softgroup_backend
    command: sh -c "poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"
    environment:
      - APP_ENV=production
      - DEBUG=False
    expose:
      - "8000"
    volumes:
      - ./docs:/app/docs
      - ./softgroup.db:/softgroup.db

    networks:
      - app-network

  softgroup_frontend:
    image: hojiakbar2806/softgroup_frontend:latest
    deploy:
      replicas: 4
    expose:
      - "3000"
    networks:
      - app-network

  softgroup_nginx:
    image: nginx:latest
    container_name: softgroup_nginx
    volumes:
      - ./nginx/softgroup.uz.conf:/etc/nginx/conf.d/softgroup.uz.conf
      - ./nginx/api.softgroup.uz.conf:/etc/nginx/conf.d/api.softgroup.uz.conf
      - ./nginx/templora.uz.conf:/etc/nginx/conf.d/templora.uz.conf
      - ./nginx/error-pages:/etc/nginx/error-pages:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - softgroup_frontend
      - softgroup_backend
    networks:
      - app-network


networks:
  app-network:    
    driver: bridge
