networks:
  app-network:
    driver: bridge

services:
  frontend:
    image: hojiakbar2806/softgroup:latest
    container_name: softgroup
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - frontend
    ports:
      - "81:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
      - ./nginx/error-pages:/usr/share/nginx/html  
    networks:
      - app-network