networks:
  app-network:
    driver: bridge

services:
  backend:
    # image: hojiakbar2806/softgroup_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    command: /bin/sh -c "flask db upgrade && poetry run gunicorn -b 0.0.0.0:8000 run:app"
    environment:
      - FLASK_ENV=production
      - DEBUG=False
      - RUN_ON_POSTGRES=True
    env_file:
      - .env  
    expose:
      - "8000"
    depends_on:
      - softgroup_db
    networks:
      - app-network

  frontend:
    image: hojiakbar2806/softgroup:latest
    container_name: frontend
    environment:
      - NODE_ENV=production
    env_file:
      - .env  
    expose:
      - "3000"
    networks:
      - app-network

  softgroup_db:
    image: postgres
    container_name: postgres
    env_file:
      - .env  
    ports:
      - "5432:5432"  
    volumes:
      - ./postgres_container:/var/lib/postgresql/data
    networks:
      - app-network

  softgroup_nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "81:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
      - ./nginx/error-pages:/usr/share/nginx/html  
    networks:
      - app-network