services:
  softgroup_backend:
    image: hojiakbar2806/softgroup_backend:latest
    container_name: softgroup_backend
    command: sh -c "poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"
    environment:
      - APP_ENV=production
      - DEBUG=False
      - RUN_ON_POSTGRES=True
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=softgroup_db
      - POSTGRES_PORT=5432
    expose:
      - "8000"
    volumes:
      - ./docs:/app/docs
      - ./logs:/var/log/softgroup
    depends_on:
      - softgroup_db
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  softgroup_frontend:
    image: hojiakbar2806/softgroup:latest
    container_name: softgroup_frontend
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    networks:
      - app-network
    volumes:
      - ./logs:/var/log/softgroup
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  softgroup_db:
    image: postgres
    container_name: softgroup_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_container:/var/lib/postgresql/data
      - ./logs:/var/log/softgroup
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  softgroup_nginx:
    image: nginx:latest
    container_name: softgroup_nginx
    volumes:
      - ./nginx/softgroup.uz.conf:/etc/nginx/conf.d/softgroup.uz.conf
      - ./nginx/api.softgroup.uz.conf:/etc/nginx/conf.d/api.softgroup.uz.conf
      - ./nginx/templora.uz.conf:/etc/nginx/conf.d/templora.uz.conf
      - ./nginx/error-pages:/etc/nginx/error-pages:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./logs:/var/log/softgroup
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - softgroup_frontend
      - softgroup_backend
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  app-network:
    driver: bridge
