networks:
  app-network:
    driver: bridge

services:
  backend:
    image: hojiakbar2806/softgroup_backend:latest
    container_name: backend
    command: /bin/sh -c "flask db upgrade && poetry run gunicorn -b 0.0.0.0:8000 run:app"
    environment:
      - FLASK_ENV=production
      - DEBUG=False
      - RUN_ON_POSTGRES=True
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - softgroup_db
    networks:
      - app-network

  frontend:
    image: hojiakbar2806/softgroup:latest
    container_name: frontend
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - app-network

  softgroup_db:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_container:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/error-pages:/usr/share/nginx/html
      - ./nginx/ssl:/etc/letsencrypt
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./ssl:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

  certbot-init:
    image: certbot/certbot
    container_name: certbot-init
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./certbot-data:/var/www/certbot
    entrypoint: "/bin/sh -c 'certbot certonly --webroot --webroot-path=/var/www/certbot --email softgroup@gmail.com --agree-tos --no-eff-email -d softgroup.uz -d www.softgroup.uz -d templates.softgroup.uz'"
    networks:
      - app-network
