services:
  backend:
    image: hojiakbar2806/softgroup_backend:latest
    container_name: backend
    command: sh -c "poetry run alembic upgrade head && poetry run uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      - APP_ENV=production
      - DEBUG=False
      - RUN_ON_POSTGRES=True
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - softgroup_db
    networks:
      - app-network

  frontend:
    image: hojiakbar2806/softgroup:latest
    container_name: frontend
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - app-network

  softgroup_db:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_container:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/softgroup.uz.conf:/etc/nginx/conf.d/softgroup.uz.conf
      - ./nginx/api.softgroup.uz.conf:/etc/nginx/conf.d/api.softgroup.uz.conf
      - ./nginx/templates.softgroup.uz.conf:/etc/nginx/conf.d/templates.softgroup.uz.conf
      - ./nginx/error-pages:/etc/nginx/error-pages:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
