"""Fix foreign keys

Revision ID: d5b5de6c2afc
Revises: 08a661ddd787
Create Date: 2024-12-29 00:40:35.188404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b5de6c2afc'
down_revision: Union[str, None] = '08a661ddd787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'in_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('in_stock', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
