name: Softgroup frontend deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build backend Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          tags: hojiakbar2806/softgroup_backend:latest
          cache-from: hojiakbar2806/softgroup_backend:latest
          push: true

      - name: Build frontend Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          tags: hojiakbar2806/softgroup_frontend:latest
          cache-from: hojiakbar2806/softgroup_frontend:latest
          push: true

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to AWS
        run: |
          ssh -o StrictHostKeyChecking=no -i "~/ssh_key" root@37.60.228.238 << 'EOF'
          cd ~/softgroup 
          git pull
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d
          sudo docker image prune -a -f
          EOF
